// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO80S9Eb7gYV_h6BhI1t2noJ_l2ItzDNI',
    appId: '1:536295333141:web:e2bf62232b15769c1cdd1c',
    messagingSenderId: '536295333141',
    projectId: 'calling-in-game',
    authDomain: 'calling-in-game.firebaseapp.com',
    storageBucket: 'calling-in-game.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBljHSTCuSgRt59tWU54AZmFs2gZQLFlHc',
    appId: '1:536295333141:android:4ff8ff1f956e421b1cdd1c',
    messagingSenderId: '536295333141',
    projectId: 'calling-in-game',
    storageBucket: 'calling-in-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLyn5U2zV1gS_HZmUAFngq5mDaIXyo7VE',
    appId: '1:536295333141:ios:affcfc6aff15a7e91cdd1c',
    messagingSenderId: '536295333141',
    projectId: 'calling-in-game',
    storageBucket: 'calling-in-game.appspot.com',
    iosClientId: '536295333141-jnkoa2d8nalged02inp4ulpo5jdt3pac.apps.googleusercontent.com',
    iosBundleId: 'com.example.callingInGame',
  );
}
